# Generated by Django 4.0.5 on 2022-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=6)),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('origin', models.CharField(max_length=3)),
                ('totem', models.CharField(max_length=20)),
                ('fide_id', models.IntegerField(default=None)),
                ('title', models.CharField(max_length=3)),
                ('standard_elo', models.IntegerField(default=None)),
                ('rapid_elo', models.IntegerField(default=None)),
                ('blitz_elo', models.IntegerField(default=None)),
                ('elo_history', models.JSONField(verbose_name='elo history')),
                ('world_rank', models.IntegerField(default=None)),
                ('continental_rank', models.IntegerField(default=None)),
                ('national_rank', models.IntegerField(default=None)),
            ],
        ),
    ]
