# Generated by Django 4.0.5 on 2022-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='blitz_elo',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='continental_rank',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='elo_history',
            field=models.JSONField(blank=True, default='', verbose_name='elo history'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_rank',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='rapid_elo',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='standard_elo',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='totem',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='world_rank',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
