# Generated by Django 4.0.5 on 2022-06-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_alter_person_blitz_elo_alter_person_continental_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='blitz_games_history',
            field=models.JSONField(blank=True, default={}, verbose_name='blitz games history'),
        ),
        migrations.AddField(
            model_name='person',
            name='rapid_games_history',
            field=models.JSONField(blank=True, default={}, verbose_name='rapid games history'),
        ),
        migrations.AddField(
            model_name='person',
            name='standard_games_history',
            field=models.JSONField(blank=True, default={}, verbose_name='standard games history'),
        ),
        migrations.AlterField(
            model_name='person',
            name='elo_history',
            field=models.JSONField(blank=True, default={}, verbose_name='elo history'),
        ),
    ]
