# Generated by Django 4.0.5 on 2022-06-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_person_birth_year_person_blitz_games_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blitz_games_history',
            field=models.JSONField(blank=True, default=dict, verbose_name='blitz games history'),
        ),
        migrations.AlterField(
            model_name='person',
            name='elo_history',
            field=models.JSONField(blank=True, default=dict, verbose_name='elo history'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rapid_games_history',
            field=models.JSONField(blank=True, default=dict, verbose_name='rapid games history'),
        ),
        migrations.AlterField(
            model_name='person',
            name='standard_games_history',
            field=models.JSONField(blank=True, default=dict, verbose_name='standard games history'),
        ),
    ]
