# Generated by Django 4.0.5 on 2022-06-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_alter_person_blitz_games_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
